<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.Kerravitarr</groupId>
    <artifactId>Cellotopia</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    
    <repositories>
           <repository>
               <id>jitpack.io</id>
               <url>https://jitpack.io</url>
           </repository>
    </repositories>
    
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>25</maven.compiler.source>
		<maven.compiler.target>25</maven.compiler.target>
		<java.version>24</java.version>
		<exec.mainClass>start.BioLife</exec.mainClass>
	</properties>
    
    <dependencies>  
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.Kerravitarr</groupId>
            <artifactId>Kerlib</artifactId>
            <version>-SNAPSHOT</version>
        </dependency>
    </dependencies>  

    
    <build>
		<!--Имя файла после сборки-->
		<finalName>${project.name}</finalName>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		<plugins>
			<!--Плагин чтобы создать сразу готовый файлик-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>1.4</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<artifactSet>
								<!-- Signed JAR files-->
								<excludes>
									<exclude>bouncycastle:bcprov-jdk15</exclude>
								</excludes>
							</artifactSet>

							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<!-- Main class -->
									<mainClass>start.BioLife</mainClass>
								</transformer>

								<!-- Use resource transformers to prevent file overwrites -->
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>properties.properties</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.XmlAppendingTransformer">
									<resource>applicationContext.xml</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>META-INF/cxf/cxf.extension</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.XmlAppendingTransformer">
									<resource>META-INF/cxf/bus-extensions.xml</resource>
								</transformer>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>
            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-compiler-plugin</artifactId>
               <version>3.14.0</version>
               <configuration>
                   <source>24</source>
                   <target>24</target>
               </configuration>
            </plugin>
		</plugins>
	</build>
</project>