/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Calculations.Configurations;
import java.util.EventListener;

/**
 *Универсальный набор:
 * Подпись, ползунок, ресет и кнопка ввода числового значения
 * @author Kerravitarr
 */
public class SettingsBoolean extends javax.swing.JPanel {
	/**Интерфейс, который срабатывает при обновлении значения*/
	public interface AdjustmentListener extends EventListener {
		public void adjustmentValueChanged(boolean nVal);
	}
	
	/**
	* Создаёт панельку настройки
	* @param nameO имя параметра (по нему берутся навазния)
	* @param defVal значение по умолчанию
	* @param nowVal текущее значение
	* @param list слушатель, который сработает, когда значение изменится
	*/
   public SettingsBoolean(String nameO, boolean nowVal, AdjustmentListener list) {
		initComponents();
		
		listener = e -> {};
		_label.setText(Configurations.getHProperty(Settings.class, nameO + ".L"));
		_label.setToolTipText(Configurations.getHProperty(Settings.class, nameO + ".T"));
		_checkBox.setToolTipText(Configurations.getHProperty(Settings.class, nameO + ".T"));
		value = !nowVal;
		setValue(nowVal);
		
		listener = list;
		_checkBox.addActionListener( e -> listener.adjustmentValueChanged(_checkBox.isSelected()));
	}
	/**Сохранить значение слайдера
	 * @param val 
	 */
	public void setValue(boolean val) {
		if(value != val){
			value = val;
			_checkBox.setSelected(val);
			listener.adjustmentValueChanged(val);
		}
	}
	/**Получить текущее значение слайдера
	 * @return 
	 */
	public boolean getValue() {
		return value;
	}
	@Override
	public void setEnabled(boolean isEnabled){
		super.setEnabled(isEnabled);
		_checkBox.setEnabled(isEnabled);
		_label.setEnabled(isEnabled);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _checkBox = new javax.swing.JCheckBox();
        _label = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(2147483647, 40));
        setLayout(new java.awt.BorderLayout());
        add(_checkBox, java.awt.BorderLayout.CENTER);

        _label.setText("jLabel1");
        add(_label, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox _checkBox;
    private javax.swing.JLabel _label;
    // End of variables declaration//GEN-END:variables
	
	/**Реальное значение*/
	private boolean value;
	/**Слушатель события, что значение в ячейке изменилось*/
	private AdjustmentListener listener;
}
