/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Calculations.Configurations;
import Calculations.Point;
import Utils.MyMessageFormat;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.EventListener;

/**
 *Универсальный набор:
 * Подпись, ползунок, ресет и две ячейки для ввода точки на экране
 * @author Kerravitarr
 */
public class SettingsPoint extends javax.swing.JPanel {
	/**Интерфейс, который срабатывает при обновлении значения*/
	public interface AdjustmentListener extends EventListener {
		public void adjustmentValueChanged(Point.Vector nVal);
	}
	
	/**
	* Создаёт панельку настройки для ввода двух чисел
	* @param nameO имя параметра (по нему берутся навазния)
	 * @param minX минимальное значение параметра Х
	 * @param defX значение параметра Х по умолчанию
	 * @param maxX максимамльное значение параметра Х
	 * @param nowX текущее значение параметра Х
	 * @param minY минимальное значение параметра Y
	 * @param defY значение параметра Y по умолчанию
	 * @param maxY максимамльное значение параметра Y
	 * @param nowY текущее значение параметра Y
	* @param list слушатель, который сработает, когда значение изменится
	*/
   public SettingsPoint(String nameO, int minX, int defX, int maxX, int nowX, int minY, int defY, int maxY, int nowY, AdjustmentListener list) {
		this();
		listener = e -> {};
		
		label.setText(Configurations.getHProperty(Settings.class, nameO + ".L"));
		labelX.setText(Configurations.getHProperty(Settings.class, nameO + ".X"));
		labelY.setText(Configurations.getHProperty(Settings.class, nameO + ".Y"));
		label.setToolTipText(Configurations.getHProperty(Settings.class, nameO + ".T"));
        spinnerX.setModel(new javax.swing.SpinnerNumberModel(nowX, minX, maxX, 1));
        spinnerY.setModel(new javax.swing.SpinnerNumberModel(nowY, minY, maxY, 1));
		
		Configurations.setIcon(reset, "reset");
		reset.setPreferredSize(BUT_SIZE);
		reset.addActionListener(e -> setValue(Point.Vector.create(defX,defY)));
		reset.setToolTipText(Configurations.getHProperty(SettingsPoint.class, "resetSlider"));

		value = null;
		setValue(Point.Vector.create(nowX,nowY));
		
		listener = list;
		spinnerX.addChangeListener((e) -> setValue(Point.Vector.create(((Number)spinnerX.getValue()).intValue(),((Number)spinnerY.getValue()).intValue())));
		spinnerY.addChangeListener((e) -> setValue(Point.Vector.create(((Number)spinnerX.getValue()).intValue(),((Number)spinnerY.getValue()).intValue())));
	}
	/** Creates new form Slider */
	private SettingsPoint() {
		initComponents();
		for (int i = 0; i < 2; i++) {
			final var spinner = i == 0 ? spinnerX : spinnerY;
			
			final var jtf = ((javax.swing.JSpinner.DefaultEditor) spinner.getEditor()).getTextField();
			jtf.addKeyListener(new KeyAdapter() {
				@Override
				public void keyReleased(KeyEvent e) {
					String text = jtf.getText().replace(",", "");
					int oldCaretPos = jtf.getCaretPosition();
					try {
						Integer newValue = Integer.valueOf(text);
						spinner.setValue(newValue);
						jtf.setCaretPosition(oldCaretPos);
					} catch (NumberFormatException ex) {
						//Not a number in text field -> do nothing
					} catch (java.lang.IllegalArgumentException ex) { //Удалили цифру, каретка уехала
						jtf.setCaretPosition(oldCaretPos - 1);
					}
				}
			});
		}
	}
	/**Сохранить значение слайдера
	 * @param val 
	 */
	public void setValue(Point.Vector val) {
		if (!val.equals(value)) {
			value = val;
			spinnerX.setValue(val.x);
			spinnerY.setValue(val.y);
			listener.adjustmentValueChanged(val);
		}
	}
	/**Получить текущее значение слайдера
	 * @return 
	 */
	public Point.Vector getValue() {
		return value;
	}
	@Override
	public void setEnabled(boolean isEnabled){
		super.setEnabled(isEnabled);
		spinnerX.setEnabled(isEnabled);
		spinnerY.setEnabled(isEnabled);
		reset.setVisible(isEnabled);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        resetAndInsert = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelX = new javax.swing.JLabel();
        spinnerX = new javax.swing.JSpinner();
        labelY = new javax.swing.JLabel();
        spinnerY = new javax.swing.JSpinner();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(2147483647, 40));
        setLayout(new java.awt.BorderLayout());

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("name");
        label.setAlignmentY(0.0F);
        add(label, java.awt.BorderLayout.NORTH);

        resetAndInsert.setLayout(new java.awt.BorderLayout());

        reset.setText("reset");
        resetAndInsert.add(reset, java.awt.BorderLayout.WEST);

        add(resetAndInsert, java.awt.BorderLayout.EAST);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        labelX.setText("X:");
        labelX.setAlignmentY(0.0F);
        labelX.setPreferredSize(new java.awt.Dimension(15, 20));
        jPanel1.add(labelX);

        spinnerX.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spinnerX.setAlignmentY(0.0F);
        spinnerX.setMaximumSize(new java.awt.Dimension(32767, 20));
        spinnerX.setMinimumSize(new java.awt.Dimension(64, 20));
        spinnerX.setPreferredSize(new java.awt.Dimension(64, 20));
        jPanel1.add(spinnerX);

        labelY.setText("Y:");
        labelY.setAlignmentY(0.0F);
        labelY.setPreferredSize(new java.awt.Dimension(15, 20));
        jPanel1.add(labelY);

        spinnerY.setModel(new javax.swing.SpinnerNumberModel(100, 0, null, 1));
        spinnerY.setAlignmentX(0.0F);
        spinnerY.setAlignmentY(0.0F);
        spinnerY.setMaximumSize(new java.awt.Dimension(32767, 20));
        spinnerY.setMinimumSize(new java.awt.Dimension(68, 20));
        spinnerY.setPreferredSize(new java.awt.Dimension(68, 20));
        jPanel1.add(spinnerY);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JButton reset;
    private javax.swing.JPanel resetAndInsert;
    private javax.swing.JSpinner spinnerX;
    private javax.swing.JSpinner spinnerY;
    // End of variables declaration//GEN-END:variables
	
	/**Размер кнопок*/
	private static final Dimension BUT_SIZE = new Dimension(20,15);
	/**Реальное значение*/
	private Point.Vector value;
	/**Слушатель события, что значение в ячейке изменилось*/
	private AdjustmentListener listener;
	/**Форматирование высплывающего окна над значением*/
	private final MyMessageFormat valueFormat = new MyMessageFormat(Configurations.getProperty(Settings.class,"scrollTtext"));
}
